### PR TITLE
Added Reusable Workflow for Generating Initial Config Branch Checksums

### PR DESCRIPTION
**Pull request by CodeGat**
In this PR:
﻿* Added reusable generate-initial-checksums.yml workflow
* Updated README.md: Added section on new generate-initial-checksums.yml reusable workflow

References ACCESS-NRI/access-om2-configs#9

### CODE REVIEW

**Review by aidanheerdegen — DISMISSED** [review]
LGTM.

I am curious about the necessity for `target-branch-name`. Well not the necessity, but won't the most common use case be for `config-branch-name == target-branch-name`?

**Comment by CodeGat** [comment]
Yes that is true - I was wondering if maybe you'd have:
`config-branch-name`: release-1deg_jra55_iaf
`target-branch-name`: dev-1deg_jra55_iaf
Or something. If there aren't any possible use cases, then I can simplify it. What do you think @aidanheerdegen ?

**Comment by aidanheerdegen** [comment]
> Yes that is true - I was wondering if maybe you'd have:
> `config-branch-name`: release-1deg_jra55_iaf
> `target-branch-name`: dev-1deg_jra55_iaf
> Or something. If there aren't any possible use cases, then I can simplify it. What do you think @aidanheerdegen ?

I can see the programming logic, but if 90% of the use cases are covered by assuming `config-branch-name == target-branch-name` then it makes it a lot simpler, and maybe easier to understand, for the person using it to just specific a single branch. 

The case for a committing to a different branch is also covered if `target-branch` is just `branch`ed from `config-branch`, e.g.
```
git checkout config-branch-name
git checkout -b target-branch-name
git push origin target-branch-name
```
and then run the simplified workflow on `target-branch-name`

**Comment by CodeGat** [comment]
Good point. I'll simplify.

**Review by aidanheerdegen — APPROVED** [review]
LGTM

**Pull request merged**
